### ISSUE TITLE
Consider using smaller base image

### ISSUE THREAD

**Issue by naamunds** [dotnet/dotnet-docker-nightly#11]
The Dockerfile in this repo is currently using an "scm" buildpack-deps image.  According to the [buildpack-deps repo](https://hub.docker.com/r/library/buildpack-deps/), the scm images add "various source control management tools".  These tools add significant size to the image and may not be critical for the base .NET Docker image.

We could perhaps use a smaller buildpack-deps image like `jessie-curl`, which is 42 MB smaller than `jessie-scm`.  We could then install just one or two source management tools on top of it (such as Git) rather than all of the ones installed by the jessie-scm image.  To reduce the size even further, we could use `debian:jessie` as the base image and then just install curl and use that instead of wget.

We should also consider making this change in https://github.com/dotnet/dotnet-docker, although the situation is somewhat different there because we plan to have a separate "slim" dotnet-docker image with minimal dependencies.

**Comment by friism** [comment]
@naamunds why do you need git?

**Comment by naamunds** [comment]
@friism It's not strictly necessary, but @MichaelSimons mentioned to me that it might be worth having in the base image, so I wanted to call it out as something to consider.

**Comment by MichaelSimons** [comment]
The Dockerfile in this repo is intended for developers to build, test, and debug .Net Core apps on.  In the RC2 time frame there are plans to add two flavors of runtime images.  
- A `slim` image that contains the minimum requirements to run a standalone .Net Core app.  
- A `sharedframework` image that is based on the `slim` image and adds to it a version of the shared framework.  This image can be used to run apps built with the shared framework (which is the default way of building apps).

A goal of the runtime images is to make them as small as possible.  These images will not be based on `buildpack-deps` images rather on plain Debian.  Once Alpine is supported, they will be based on it.  As for the developer intended image (which is what the preview image is), I was thinking it would make sense for it to be based on a `buildpack-deps` image.  Having git installed in a developer targetted environment is rather convenient IMO.

**Comment by naamunds** [comment]
As @MichaelSimons mentioned, it makes sense for the image with the .NET CLI tools to include common developer tools such as Git by being based on the `buildpack-deps:jessie-scm` image.  The [official images repo](https://github.com/dotnet/dotnet-docker) has runtime images which have mimimal dependencies in addition to CLI tools images using `buildpacks-deps:jessie-scm`; this is consistent with other products such as [Golang](https://hub.docker.com/_/golang/).

This repo just contains an image with the CLI tools, so I'm closing this issue.
