### ISSUE TITLE
Some images built from the same Dockerfile have different layers

### ISSUE THREAD

**Issue by naamunds** [dotnet/dotnet-docker-nightly#112]
This repo has several images which have multiple tags; for example, `1.0.1-runtime` and `1.0-runtime` point to the same image.  For some images, we are assigning the same image multiple tags, either by the build hooks or the Nano Server VSTS build definitions.  For other images, we have multiple entries in the Docker Hub Build Settings for the same Dockerfiles to be built with different tags.

In the former case, the image digests are the same (meaning the tags point to the exact same image). In the latter case, the expectation is that the images should have different digests but contain the same layers.  However, this is currently not the case for some images; for example, `microsoft/dotnet-nightly:1.0-sdk-msbuild` and `microsoft/dotnet-nightly:1.0.1-sdk-msbuild` contain three different layers, which can be seen with the `docker inspect` command.  This means that users who pull both tags will have separate layers for them on their machines, which takes up a substantial amount of extra space and increases download times.

**Comment by MichaelSimons** [comment]
Docker Hub auto-build functionality does not have support for multi-tagging an image.  Currently multiple build rules are defined but this results in images that don't share layers.  To fix this, build hooks must be used.
