### ISSUE TITLE
We should rename this repo and the Docker Hub repository to something other than "preview"

### ISSUE THREAD

**Issue by dleeapho** [dotnet/dotnet-docker-nightly#14]
Originally we had named this image dotnet-preview to match the fact that the image uses the .NET CLI Preview channel but with the advent of "preview1" as a version name in the CLI we risk confusion. We should find a better name-- something like "nightly". @blackdwarf @glennc do you have suggestions.

**Comment by glennc** [comment]
I am ok with Nightly. @blackdwarf what do you guys refer to the builds of the CLI on GitHub? Do you have a name?

**Comment by naamunds** [comment]
I synced up with @blackdwarf over email, and he agrees with "nightly".  Also, the image tag will be named "rel-1.0.0" to align with the CLI channel/branch name.

The command to pull the image will be:
`docker pull microsoft/dotnet-nightly:rel-1.0.0`
