### ISSUE TITLE
Create tag-details.md

### ISSUE THREAD

**Issue by kendrahavens** [dotnet/dotnet-docker-nightly#207]
### Benefits of adding tag-details.md
* Help provide more info on the breakdown of what is in each Docker image
* Help explain the naming conventions behind tag schema
* Other repos use this solution to help new users understand their repo

**Comment by MichaelSimons** [comment]
FYI, I have been typically using https://github.com/dotnet/dotnet-docker/issues to track issues for nightly as well.  Using the official repro provides more visibility to users on what is coming down the pipe (e.g. it is happening in nightly first).  Closing this and tracking with https://github.com/dotnet/dotnet-docker/issues/212.

**Comment by kendrahavens** [comment]
Sounds good!
