### ISSUE TITLE
The repository should be updated to pick up the next-release train of the CLI bits

### ISSUE THREAD

**Issue by dleeapho** [dotnet/dotnet-docker-nightly#22]

**Comment by MichaelSimons** [comment]
Along with updating the Dockerfile, the [Maestro hook](https://github.com/dotnet/versions/blob/master/Maestro/subscriptions.json#L151) will need to be updated so that the Docker Hub build gets triggered when a new CLI build is completed for the 'next-release'.

**Comment by naamunds** [comment]
Leaving open until the Maestro hook is updated.
