### ISSUE TITLE
Delete dotnet-preview Docker Hub repo

### ISSUE THREAD

**Issue by naamunds** [dotnet/dotnet-docker-nightly#24]
As part of the repo rename (see https://github.com/dotnet/dotnet-docker-nightly/issues/14), the [dotnet-preview Docker Hub repo](https://hub.docker.com/r/microsoft/dotnet-preview/) has been superseded by the [dotnet-nightly Docker Hub repo](https://hub.docker.com/r/microsoft/dotnet-nightly/). The old repo has been frozen, and the plan is to delete it after a period of time which allows developers who are using the repo to react to the change.

**Comment by MichaelSimons** [comment]
@dleeapho, @naamunds - I propose it is time we clean this up.  Thoughts?

**Comment by naamunds** [comment]
I agree that we should delete the dotnet-preview repo now.  It looks like very few people are using it, and for the ones who are still using it, they're probably not aware of the dotnet-nightly repo, so this will force them to update.

**Comment by MichaelSimons** [comment]
The repo has been deleted.
