### ISSUE TITLE
The multi-arch based tags for 2.0 should point to debian:stretch based images

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker-nightly#321]
Currently the multi-arch based tags refer to debian:jessie based images.  Microsoft should be providing the most secure base images that it can - which is believed to be debian:stretch.  The jessie based images should still be available via a `-jessie` suffixed tag.

**Comment by zafields** [comment]
Can you use `debian:stretch-slim`, instead of `debian:stretch` to minimize the image size? Not only would it save space, but having less libraries installed should also reduce the attack surface.

**Comment by MichaelSimons** [comment]
@zafields, can you please open a separate issue to discuss using the slim images?  This issue is about changing the multi-arch tags to point to the existing stretch based image.
