### ISSUE TITLE
Update tagging for preview3

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker-nightly#333]
Need to change tag names from 2.0.0-preview2 to 2.0.0-preview3 to match the .NET Core artifacts contained in the images.

**Comment by natemcmaster** [comment]
It looks like some preview3 builds made it to Docker hub tagged as preview2 before the CI run was cancelled (see `microsoft/dotnet-nightly:2.0.0-preview2-sdk-stretch`). Can we re-spin the build for 60b4217ce492158922a45ab169cf9097f7c93e78 so the tags match the content?

This will help me verify preview2 builds of aspnetcore before we release.

**Comment by MichaelSimons** [comment]
@natemcmaster - yes I have kicked off a new build.

**Comment by natemcmaster** [comment]
@MichaelSimons thanks. The preview2 tags have been fixed.
