### ISSUE TITLE
[Tests] CreateTestAppWithSdkImage should be using the imageDescriptor.SdkVersion

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker-nightly#450]
This is a regression - https://github.com/dotnet/dotnet-docker-nightly/commit/ef3875737c10c78fee915149e9cf38efea124848#diff-6d015b054fda67c172395b42424cf656R113

The result is the tests are using the incorrect sdk tag in some scenarios.

**Comment by ravimeda** [comment]
Thanks for catching this!
