### ISSUE TITLE
Invoke-WebRequest failures in CI.

### ISSUE THREAD

**Issue by ravimeda** [dotnet/dotnet-docker-nightly#456]
## Steps to reproduce the issue
1. Invoke several CI jobs. For example, submit a couple dummy PRs.
2. Wait for a CI job to fail due to an error at `Invoke-WebRequest` command. For example, https://ci.dot.net/job/dotnet_dotnet-docker-nightly/job/master/job/NanoServer_2.0_prtest/215/console

## Expected behavior
No `Invoke-WebRequest` failures.

## Actual behavior
`Invoke-WebRequest` command fails on a CI machine. Once this failure occurs, all subsequent jobs on the machine will fail at the same `Invoke-WebRequest`. 

Only workaround available is to delete the machine, and let CI recreate a new one.

**Comment by MichaelSimons** [comment]
Note: This is related to the Nano Server legs.  Linux CI is pretty stable.

**Comment by MichaelSimons** [comment]
Assigning to Ravi to investigate.

**Comment by ravimeda** [comment]
https://github.com/dotnet/dotnet-ci/pull/863
