### ISSUE TITLE
Decide what to do with microsoft/nanoserver-insider-dotnet Docker Hub repo

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-docker-nightly#471]
This repo was created to host Windows Insider builds for the Windows Server 1709 release.  Now that the release is GA, the repo's readme is out of date and the Dockerfile links are broken.  Would it make sense to update the readme to indicate it is obsolete because of the 1709 release?  After some time goes by it may make sense to delete it or it could be left in the obsolete state with the possibility of using it during the next release cycle.

**Comment by MichaelSimons** [comment]
Should note that these images are not being serviced and we will delete the image Jan 1 2018

**Comment by kant2002** [comment]
Just pass by and notice that repo is still on [Docker hub](https://hub.docker.com/r/microsoft/nanoserver-insider-dotnet/).

**Comment by MichaelSimons** [comment]
@kant2002  - thanks for the notice - I deleted the repo.
