### ISSUE TITLE
Docker assets should be cleaned up towards the end of a CI check

### ISSUE THREAD

**Issue by ravimeda** [dotnet/dotnet-docker-nightly#529]
## Steps to reproduce the issue
1. Submit a dummy PR. To avoid merging the changes, add `[WIP]` in the title.
2. Wait for CI checks to finish
3. Verify if Docker assets are cleaned up towards the end of each CI check

## Expected behavior

All Docker assets that were created while running the test should be cleaned up.  

Running `docker system prune -a -f` would clear up everything including base OS image such as Windows Server Core.  These images are several GiB in size, and are not modified during a CI run. Only time these images need to be re-pulled is when a newer image is available in the registry.  Hence it would be more efficient to avoid deleting such base OS images, and only delete images that are built during each CI.

## Actual behavior

`%ProgramData%\Docker` that contains the images pulled and created during the CI check is not cleaned up.  This can result in filling up the disk, and the test VM becomes unusable.

**Comment by ravimeda** [comment]
Attempt to fix this issue through https://github.com/dotnet/dotnet-docker-nightly/commit/96618736802d654be05d1165eed998583e8f0a68 introduced a regression.  This is because, the statement `docker ps -a -q | ForEach-Object { docker rm -f $_ }` when run inside a container can delete the container itself. Exit code thrown is 137.  Linux CI that runs in a container with _testrunner_ image is broken.  Windows CI is fine since it does not run in a container.

**Comment by MichaelSimons** [comment]
Fixed.
